### ISSUE TITLE
Introduce root model object into model viewer trees

### ISSUE THREAD

**Issue by bfitzpat** [fabric8io/data-mapper#120]
When viewing the source and target models in the bottom panes, the root node is not displayed. Though it is described textually in the tab name, it would be good to show this node explicitly to the user so they have a better handle on where the listed model objects in the tree are coming from.

**Comment by bfitzpat** [comment]
Here's the PR for this work - https://github.com/fabric8io/data-mapper/pull/121

**Comment by kcbabo** [comment]
pushed
