### ISSUE TITLE
filtering and display updates for model viewers

### ISSUE THREAD

**Issue by kcbabo** [fabric8io/data-mapper#122]
1) Place an asterisk next to fields that have been mapped already.  Keep in mind that the model view will need to be refreshed (and asterisks removed) when a mapping is deleted up top.

2) Default to not showing type info in the model viewers.  The user can always see the type info by toggling the filter for displaying types.

**Comment by jpav** [comment]
I'd also suggest defaulting to unqualified types when they are shown, using the same reasoning.

**Comment by bfitzpat** [comment]
jpav - Are you agreeing with #2 in your comment? Or saying something else?

**Comment by jpav** [comment]
I'm agreeing.  To summarize, I think the default view should just show elements without types.  If the user clicks on the filter to show types, they should be initially shown unqualified.  The second filter button would show types fully qualified.

IOW, the filter buttons would effectively do the opposite of what they do now: clicking the first filter button would show types, not hide them, while clicking the second filter button would show qualification, not hide it.

Hope that helps.

**Comment by bfitzpat** [comment]
Beautiful. Just making sure. Apparently I haven't had enough coffee yet this morning. :)

**Comment by kcbabo** [comment]
So we have two filter buttons today:

- Button 1 : show/hide types.  This will default to hide all types with this change.
- Button 2 : show mapped/unmapped; unrelated to button 1.

So are we saying that button 1 would have three states:
- types not shown
- types shown in short form
- types shown in long form

Or are we adding a second button which sets long/short form for types?

**Comment by bfitzpat** [comment]
Same buttons as before.

The default for the viewer is to not show types. So when you click button 1, it shows the types.

All fields are shown by default. Mapped fields will have an asterisk on the left side. 

Button 2 will hide mapped fields. 

I wasn't thinking of adding a third state for "short types" vs "long types" unless you think we need it.

Did I miss something in my caffeine reduced delirium?

**Comment by bfitzpat** [comment]
![data-mapper-updated-decorators](https://cloud.githubusercontent.com/assets/530878/6169391/643ff1ba-b28a-11e4-8d6a-5ae105f3a928.png)

**Comment by bfitzpat** [comment]
![data-mapper-updated-decorators2](https://cloud.githubusercontent.com/assets/530878/6169417/97f5c91c-b28a-11e4-8eee-8f79f2aedebe.png)

**Comment by jpav** [comment]
While I kind of like the idea of a 3-state button to do all of this, I'm not sure there's much precedence in Eclipse for something like that.  What I was suggesting is to flip the meaning of our existing two toggle buttons:

Toggle Button 1: Initially, when not toggled, types are not shown (as you requested).  Toggling the button on would show the types, but initially unqualified (or more accurately, show types however indicated by the state of Toggle Button 2).
Toggle Button 2: Initially, this button would be disabled, and enabled only after Toggle Button 1 has been toggled on.  After being enabled (i.e., after types are shown), toggling the button on would show fully-qualified types.

**Comment by jpav** [comment]
I kind of liked the idea of always (i.e., with the asterisk) showing mapped fields if they haven't been filtered, which is what I think Keith was initially asking for.  I.e., the user would not have an option to toggle the asterisk off beyond the existing filter to not show these fields at all.

**Comment by bfitzpat** [comment]
Right now I don't give the user the option of turning off the asterisk other than hiding the mapped fields.

**Comment by kcbabo** [comment]
OK, I think I have managed to patch this discussion together in my mind now. :-)

Adding the asterisk is in addition to allowing the user to filter out mapped fields.  So we would always mark a mapped field with an asterisk and the user has the option of showing/hiding mapped fields in the model with the filter button.

I think it's a nice option to abbreviate the type, but it will require a third button unless we do the funky three-state thing.  Let's file an issue for now and we can discuss how to handle that in a future milestone.

**Comment by jpav** [comment]
As a bit of an aside, what do you guys think of changing the visual indication of a list to one of these (using a field called names, with of type of a list of Strings as an example):

name: List of string (my preference, maybe with the "List of" colored gray instead of black using a styled label provider)
name: string... (again, maybe with the ellipses ("...") colored gray)

Also, I'm thinking we'd want to make types we treat as primitives, like String and primitive wrapper classes (e.g., Integer, etc.) be lowercase: integer vs Integer

**Comment by jpav** [comment]
Oh, crap, sorry, just realized I'm the one getting the button functionality messed up.  I didn't read the previous message close enough. :-(

Yeah, the qualification button isn't as important, and right now would require yet another filter button, so it makes sense to deal with that later.  Sorry for the confusion. But, I still think we should consider the aside I just posted...

**Comment by jpav** [comment]
So, to undo the confusion I just introduced a bit ago, ignore my previous description of Toggle Button 2.  That would actually be a newly introduced third toggle button.  Sorry.

**Comment by bfitzpat** [comment]
jpav - can I see an example of what that might look like in a tree? (the updated textual decorators)

**Comment by bfitzpat** [comment]
I just put a PR up - https://github.com/fabric8io/data-mapper/pull/125 - with my latest changes. I'm happy to tweak what we're displaying as far as the text decorator for types. So this isn't final - just throwing it out there so you know what it looks like.

**Comment by jpav** [comment]
Here's my example:



And here's the code I used to create it:

	new StyledCellLabelProvider() {

            private static final String LIST_OF = "List of ";

            @Override
            public void update( ViewerCell cell ) {
                final Model model = ( Model ) cell.getElement();
                cell.setStyleRanges( null );
                if ( showFieldTypesInLabel ) {
                    String type = model.getType();
                    if ( type.startsWith( "[" ) ) {
                        cell.setText( model.getName() + ": " + LIST_OF + type.substring( 1, type.length() - 1 ) );
                        cell.setStyleRanges( new StyleRange[] { new StyleRange( cell.getText().indexOf( LIST_OF ),
                                                                                LIST_OF.length(),
                                                                                getDisplay().getSystemColor( SWT.COLOR_DARK_GRAY ),
                                                                                null) } );
                    } else cell.setText( model.getName() + ": " + type );
                } else cell.setText( model.getName() );
                super.update( cell );
            }
        } );

**Comment by bfitzpat** [comment]
Ok - I've updated it slightly to work with my updates as follows... 
![data-mapper-updated-decorators3](https://cloud.githubusercontent.com/assets/530878/6174457/186d2baa-b2ac-11e4-9ebf-97e2aa31ad9e.png)

**Comment by kcbabo** [comment]
pushed
