### ISSUE TITLE
Evaluate save strategy

### ISSUE THREAD

**Issue by kcbabo** [fabric8io/data-mapper#123]
We are pretty greedy about persisting updates to the underlying config model right now.  Any time the user takes action, we save the config.  We might want to consider marking the config as dirty and allow the user to drive the save process.  I imagine this has some implications from an undo/redo standpoint as well.

**Comment by jpav** [comment]
I'm not a fan of this approach.  I'm seeing more and more apps go the direction of auto-save, removing it from the user's concern.  OSX, mobile, and web apps all seem to be following this paradigm this pattern more.  Plus, as you mentioned (although I can't tell which way you were thinking the implications would go), this will make undo/redo much easier once we address it.  And we avoid the dirty "asterisk" issues with the editor.

**Comment by kcbabo** [comment]
The primary issue with auto-save is that if someone is trying some stuff out and wants to bail, it becomes really difficult to "rollback" to the appropriate save point since you've been saving all along.  Let's say I have a map where I'm hacking on some stuff and it just turns out to be a disaster; not what I wanted at all.  If I haven't saved yet, then I can just close the editor and confirm that I don't want to save my changes.

**Comment by jpav** [comment]
Right, but I'd argue 1) lots of changes that need to be rolled back I don't think is the norm, and 2) that's what "Replace from local history" is for (which I don't think is that difficult).  But just my opinion...

Having said that, implementing the use of save wouldn't be that big of a deal code-wise.

**Comment by kcbabo** [comment]
Yeah - my motivation with this issue is to throw all the options out on the table and just decide what the best approach is.  I’m definitely not saying auto-save is evil - just that we need to have an overall strategy w/r/t save and to make sure it’s clear/consistent for end users.

**Comment by bfitzpat** [comment]
The undo/redo stack is basically what we're talking about here, right? So the ability to map something or make a change and then undo it if they realize it's not what they wanted. I think as we add more and more functionality to the mapper, this is going to be a necessary and expected thing. 

The file history is one way to go, but in my local testing that doesn't seem to be actually being updated (no history is generated if I add/remove mappings, close the file, and reopen for example) - so we need to investigate that a bit.
