### ISSUE TITLE
don't default camel context file location

### ISSUE THREAD

**Issue by kcbabo** [fabric8io/data-mapper#139]
We should not default the camel context location in the new transformation wizard.  Allow the user to select the one they want.

Bonus points : remove the src/main/resources from the value that's displayed to the user when selected.  We can always keep that under the covers in the UI.

**Comment by jpav** [comment]
I thought the context could be anywhere on the class path, so the path would matter? Could it be in src/Java? And must be in the same project? So if there is just one context that exists in the project, why wouldn't we auto select it?

**Comment by bfitzpat** [comment]
We decided it has to be in the same project and on the project classpath somewhere... Could be in src/java, but right now we expect it to be in src/resources I think. And the map-3 example offers TWO different route files. I think the days of the single route in a project are out. :)

I've done some work here to address both issues - https://github.com/fabric8io/data-mapper/pull/140

@kcbabo  Can you test this when you get a chance to make sure it does what you want it to? Thanks

**Comment by kcbabo** [comment]
The Camel configuration we are talking about here will always be an XML file and won't be in src/main/java.  It's possible that it could be in a directory other than src/main/resources (e.g. src/main/config), but that would require additional configuration with the maven resources plugin to get those into the deployment.

Any project can have multiple camel context files.  The m3 app has two now just to demonstrate that we can handle spring and blueprint config.  It's unlikely that a real project would mix those config types.  In the future, I might break up our examples to be more focused (e.g. one for spring, another for blueprint, etc.).

**Comment by jpav** [comment]
> On Feb 13, 2015, at 6:32 PM, Keith Babo <notifications@github.com> wrote:
> 
> The Camel configuration we are talking about here will always be an XML file and won't be in src/main/java. It's possible that it could be in a directory other than src/main/resources (e.g. src/main/config), but that would require additional configuration with the maven resources plugin to get those into the deployment.
> 
> Any project can have multiple camel context files. The m3 app has two now just to demonstrate that we can handle spring and blueprint config. It's unlikely that a real project would mix those config types. In the future, I might break up our examples to be more focused (e.g. one for spring, another for blueprint, etc.).
> 

I understand they can have more than one, but all I was saying is if there is exactly one, why not auto select it? Maybe I'm just being too specific about the concern, so sorry if that's the case.

**Comment by jpav** [comment]
Now I'm thinking I misunderstood what you meant by default the location. You meant don't assume the old hard coded value of src/main/resources/…. I keep reading these damn emails too quickly. 😒
