### ISSUE TITLE
Add "expand all" button to model viewers

### ISSUE THREAD

**Issue by kcbabo** [fabric8io/data-mapper#142]
We have a collapse all button, but no expand all button.

**Comment by jpav** [comment]
I'm not sure if this is a good idea, at least for right now.  There's not much of a precedence in Eclipse (like in Package Explorer) to open a tree entirely with a single click of the button.  If the tree is large, this is rarely a good idea for the user.  But the bigger issue is memory.  In my experience, there have been several models that will simply throw you into an Out Of Memory error when this is attempted.  At a minimum, I think we should wait until we have some type of weak reference support for our models.

**Comment by kcbabo** [comment]
That's a fair point.  I imagine we could use the tree size to get a sense on whether it's manageable to do so and implement an arbitrary limit to prevent any display/memory issues.  I would think display area would be an issue before memory since anything over 1000 nodes is gonna be a mess in that view if it's all expanded.  Then again, I don't know how much of a memory pig Eclipse is with tree views. :-)

**Comment by bfitzpat** [comment]
John is definitely right in this case. I would worry about the potential size and memory footprint as well. There are probably ways around it, but it can be a hairy, ugly mess at times.

That said, we could probably start stashing some file/project-specific settings behind the scenes in the project metadata in Eclipse to keep track of the last node selected and whether it was expanded or not, filter button state, etc. - that might help persist a bit of state between openings of the editor.

**Comment by jpav** [comment]
> On Feb 16, 2015, at 8:33 AM, Keith Babo <notifications@github.com> wrote:
> 
> That's a fair point. I imagine we could use the tree size to get a sense on whether it's manageable to do so and implement an arbitrary limit to prevent any display/memory issues.
> 

Unfortunately, you can't determine the Eclipse tree size without expanding everything under the covers first.  The total size has to come from the back end, for which in my experience, memory can be just as much a concern.  And if you're using weak references on the backend model, you won't necessarily know the size up front (but that depends entirely on how changes to the model are handled, of course).  Plus, it would be a new/unusual precedent to change the GUI behavior (i.e., whether an expand all button is visible/enabled) based upon the size of the tree's contents.

> I would think display area would be an issue before memory since anything over 1000 nodes is gonna be a mess in that view if it's all expanded. Then again, I don't know how much of a memory pig Eclipse is with tree views. :-)
> 

Both of these are concerns, but it depends with the latter.  Eclipse does have some mechanisms to use "virtual" trees that help with the memory impact, but I'm not sure about the details yet.  But I'd certainly be concerned about the former.  This would be pretty non-standard in Eclipse also, but what do you think about auto-expanding the tree if it's size is less than some amount?  Again, we might have to back that out eventually if we get to using weak references in the backend and sizes aren't always available up front...

**Comment by kcbabo** [comment]
The model tree in core is super light, so it should not be a problem to implement size efficiently.  Should be simple enough to test it at a tree size of 10000 just to be sure.  If a user has a model with > 10000 nodes, then mapping overall is going to be pretty horrific.
