### ISSUE TITLE
Cannot create data map

### ISSUE THREAD

**Issue by patrikjonsson333** [fabric8io/data-mapper#160]
Hi
I have tried different approaches to use the installed data-mapper, as described in:
https://github.com/fabric8io/data-mapper/wiki/Tooling-Installation

I manage to install JBoss Tools Integration Stack.
Then I install the: JBoss Fuse Tooling Apache Camel Editor
Finally I install the milestone 3 tooling archive.

I then install the map-0 example.

However, when I try to create a map, it fails as I click Finish in the New Data Mapping wizard.
It says: "Unexpected error: system ID "...." isn't absolute.

Did I set something up incorrect?

Patrik

**Comment by jpav** [comment]
The map-x examples apply to an earlier version of data mapper.  You should instead download the examples from here: https://github.com/fusesource/fuseide/tree/master/examples/transformation

**Comment by hlkubavat** [comment]
I have tried with both the examples, but giving the same above error that was faced by Patrik
