### ISSUE TITLE
Add filter toggle to editor

### ISSUE THREAD

**Issue by jpav** [fabric8io/data-mapper#26]
When on, items in the data browsers that have already be mapped will be hidden.

**Comment by bfitzpat** [comment]
Ok, so I have in place some early code around this filtering idea. 
* Waiting on a utility method in Core to tell whether a field in a Model (perhaps "isFieldMapped(Model, String)" where the String is the field name) is mapped 
* Have functionality that changes the model label to show or hide the data type

On the "show/hide (exclude fields from the view)" request... it would be design-time only at this point unless there's a way to cache the fact that the user wants to hide such things. So each time they open the mapper, they would need to re-hide those fields. We *might* be able to store these preferences in the project's metadata in eclipse, but do we want to stash these kinds of user preferences in the mapping file itself?

**Comment by bfitzpat** [comment]
Work in progress is located here - https://github.com/bfitzpat/data-mapper/tree/issue26

**Comment by bfitzpat** [comment]
I've updated my branch with the latest code and have it working, though it's ugly right now. You can see the code in this PR - https://github.com/fabric8io/data-mapper/pull/112

**Comment by kcbabo** [comment]
pushed
