### ISSUE TITLE
create an eclipse camel editor extension plugin for the transform: endpoint editor

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/data-mapper#28]
once the camel route editor has an extension point https://issues.jboss.org/browse/FUSETOOLS-1213 we should try implement it so we can provide a custom form to view the configuration of the endpoint (input / output data formats, xsd/json schema files, dozer mapping links) so folks can easily click on a transform icon in the palette, then in the Properties tab click on a link to the dozer file / xsd / json schema etc. Then folks have an easy way to navigate from a route to all the mapping files/editors

**Comment by kcbabo** [comment]
This will happen in m4 when we take care of https://github.com/fabric8io/data-mapper/issues/79 .  The extension point we need already exists, but some config model support we need is not there yet.  We will help to contribute this in the upcoming Fuse tooling release.

**Comment by kcbabo** [comment]
Done.
