### ISSUE TITLE
Mapping to destination with grandchildren loses context

### ISSUE THREAD

**Issue by jewzaam** [fabric8io/data-mapper#69]
The example I have is in https://github.com/jewzaam/data-mapper-test and is summarized like this:

* XML to XML mapping
* source is sequence of elements
* destination is complex types

Specifically for this issue, I tried mapping one of the source elements `login` to a destination element that is two complex types deep.

Source:
```xml
<SourceUser>
    <Login>jdoe</Login>
</SourceUser>
```

Destination (expected):
```xml
<DestinationUser>
    <Person>
        <Credientials>
            <Login>jdoe</Login>
        </Credientials>
    </Person>
</DestinationUser>
```

When I drag the login field to person/credientials/login in the data mapper UI this is what ends up in the dozer xml:

```xml
        <field>
            <a>login</a>
            <b>credientials.login</b>
        </field>
```

which doesn't work.  It should instead be:

```xml
        <field>
            <a>login</a>
            <b>person.credientials.login</b>
        </field>
```

which after manual update does work.

**Comment by kcbabo** [comment]
pushed
