### ISSUE TITLE
Changing class in mapping editor doesn't update camel context

### ISSUE THREAD

**Issue by jewzaam** [fabric8io/data-mapper#72]
The camel context endpoint definition references the classes mapped.  If you select a different root class to map in the data mapping editor this class reference is not updated.

Requires multiple classes with `@XmlRootElement` in the example I'm using ([data-mapping-test](https://github.com/jewzaam/data-mapper-test)).  In that repo I have added this annotation to `destination.IdentifiersType` if you want to try it out.

**Comment by bfitzpat** [comment]
Just updated and it works nicely with the fix to saving the camel config - PR is here - https://github.com/fabric8io/data-mapper/pull/119

**Comment by kcbabo** [comment]
pushed
