### ISSUE TITLE
Update display characteristics of mapping operations view

### ISSUE THREAD

**Issue by kcbabo** [fabric8io/data-mapper#80]
After using the editor with some larger models and getting feedback from users, it would be nice to see the following updates to the mapping operations view in the editor:
- Decrease the % size of the operations view compared to the model views - make the operations view smaller and the model views larger.
- Allow the operations view to be resized, which would allow users to adjust the size as necessary.
- Allow the operations view to be minimized.

**Comment by bfitzpat** [comment]
So to summarize, we're looking for are:
* A slider between the top and bottom panels
* Resizable columns for the table in the top panel (Source Item/Operation/Target Item)
* Sliders between the source, operation ("=>"), and target areas of the bottom panel

Is that correct?

**Comment by bfitzpat** [comment]
Created a PR here - https://github.com/fabric8io/data-mapper/pull/86

It includes the three bullet points in my last comment.

**Comment by jpav** [comment]
I wasn't envisioning all of this.  It seems like the only thing we were missing was the slider between the operations view at top and the model views at bottom.  Resizing the columns seems unnecessary in both top and bottom, especially if that includes resizing the operation column in top/bottom.  Being able to resize the entire editor, along with being able to scroll within each model view, seems more than sufficient.  I don't like the idea of adding the extra visual complexity if it's not really warranted.

**Comment by kcbabo** [comment]
Thanks for banging this out @bfitzpat.  I played around with it a bit and have the following feedback:
- I would leave out the resize of the model views and the operations view at this point.  It was interesting to play around with, but I don't think it's required now and we should probably see how the layout pans out before deciding what else can be resized.
- The slider for the top/bottom panel resizing works great.  Is there any chance we could have a small visual anchor (e.g. line/bar) that indicates where a user would click in order to adjust the sizing?  It took me a second to find the spot where I could actually slide the panel up/down.
- One thing resizing the model views revealed to me is that we don't have scroll bars on those views right now.  I think that would be good to add.
- Can we adjust the default % for the top panel (operations view) to be closer to 25%?  People can size up or down from there, but a 25/75 split for top/bottom seems better to me for people just starting out on a map.

**Comment by bfitzpat** [comment]
I'll see what I can do guys. Thanks for the feedback.

**Comment by bfitzpat** [comment]
Updated the PR as requested. Let me know if there are any other tweaks guys!

**Comment by jpav** [comment]
AFAICT, everything's been addressed here.  The model views already have scroll bars, so maybe they just weren't noticed since they appear only as necessary.
