### ISSUE TITLE
UI: add constant mapping capability

### ISSUE THREAD

**Issue by kcbabo** [fabric8io/data-mapper#81]
Provide UI support for mapping a constant value to a target model field.  Required capabilities:
- Define a new constant
- Edit/remove a constant
- View defined constants
- Assign a constant to a target field

**Comment by jewzaam** [comment]
+1

**Comment by jpav** [comment]
It seems like we could approach this a few different ways.  For one, it's not clear to me whether it's necessary to really maintain a set of constants.  It obviously depends on the real use cases, but it seems like most of the time I've seen the need to provide constants in a mapping, the constants only apply to the one field being populated; other fields that require constants will often require different values.  Would it be better for the user to just click on a target field in the target model and press a button to indicate a constant mapping should be created, followed by some type of dialog or dynamically displayed field to enter that constant?  If not, then there is also a scope issue to address.  Bearing all that in mind, here are the four options as I see them I'd like to get feedback on:

1. Do not maintain a set of constants, rather allow the user to enter the constant each time a constant mapping is created.
1. Maintain a set of constants that are scoped to each Dozer config
1. Maintain a set of constants that are scoped to each project
1. Maintain a set of constants that are scoped to the workspace

All but the first option will require the constants to be persisted within the project explicitly within a visible file or implicitly via its state location.  Thoughts?  Other options?

**Comment by kcbabo** [comment]
I feel we can start with option 1 and build to option 2.  A few of the reasons why I think option 2 is where we want to go long term:

- Even with option 1, we will need to extend Dozer configuration to have the concept of a literal value for the "from" side of the mapping.  So we are storing the config somewhere anyway.
- Having the idea of a constant pool in the mapper is a bit more flexible for mappings as the value can be changed in one place if it's used in multiple locations.  This is particularly important if a constant is referenced in a custom mapping as those could be tough to track down.
- IMO, being able to define a constant and drag that to the target preserves our general mapping flow whereas starting on the target side is a bit of a change-up.

Starting with option 1 seems like a nice first step as it's not a huge investment of time and it will definitely satisfy the requirement.  I think we should keep option 2 in the picture though, even if it gets bumped to a future milestone.

**Comment by jewzaam** [comment]
Transformations I have seen to date have included many constants that get reused a lot.  They tend to be static, but it's critical that the values used in each place are identical.  The risk with having the user enter values each time is the user making a mistake.  Now, there should be tests they write to catch that but who knows.

**Comment by kcbabo** [comment]
BTW, I think there could be a smooth transition/interplay between options 1 and 2.  Once we make the constant pool visible in the editor, the user would still have the choice of:

a) Going the option 1 route and right-clicking on a target node.  At this point, they would be prompted for the constant name and value.
b) Adding the ability to add a constant and then view the constant pool which could serve as a source for a mapping (e.g. drag constant to target field).
