### ISSUE TITLE
Update package/feature/plugin naming for tools

### ISSUE THREAD

**Issue by kcbabo** [fabric8io/data-mapper#90]
Change the top-level name to "Fuse Data Mapper" and the wizard name to "Fuse Data Mapping".

Package and feature/plugin ids should be changed as well.  Most likely to "org.jboss.tools.fuse.datamapper" but I'm waiting on confirmation from Max on whether we can use "org.jboss.tools" as the root.

**Comment by jpav** [comment]
Is o.j.t.fuse.transformation/transform/xform, or something similar, an option?  I was hoping to change the names of the wizard/editor/etc., to "Transformation <Wizard/Editor>".

**Comment by kcbabo** [comment]
We would have full control of what comes after o.j.t.fuse, so transformation/transform is definitely an option.
